### ISSUE TITLE
Build error on v0.34.x branch

### ISSUE THREAD

**Issue by conorsch** [informalsystems/CometMock#14]
When I try to build the binary on the `v0.34.x` branch, I encounter an error:

```
❯ go install ./cometmock/
# github.com/informalsystems/CometMock/cometmock/abci_client
cometmock/abci_client/client.go:288:106: block.Evidence.Evidence.ToABCI undefined (type "github.com/cometbft/cometbft/types".EvidenceList has no field or method ToABCI)
cometmock/abci_client/client.go:311:118: undefined: abcitypes.Misbehavior
cometmock/abci_client/client.go:711:11: assignment mismatch: 1 variable but a.CurState.MakeBlock returns 2 values
```

It appears this was introduced by https://github.com/informalsystems/CometMock/commit/73bdb02539ac03dfde74c0167a4301f0791a8fbb ; if I revert just that commit, then I'm able to build again. 

Builds on `main` and `v0.37.x` work just fine, no problems there.

**Comment by p-offtermatt** [comment]
Thank you for creating the issue!
This has been fixed in https://github.com/informalsystems/CometMock/tree/aa1a91e6b29164bcbff6efdd532c26246afcbf23. Sorry for the inconvenience.

The automated testing for CometMock itself is not quite sufficient and this is something I do need to fix; related issue https://github.com/informalsystems/CometMock/issues/16
